/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControladorHabitacion;
import control.ControladorPago;
import control.ControladorRegistro;
import control.ControladorReserva;
import control.ControladorServicioCliente;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Habitacion;
import modelo.Pago;
import modelo.Registro;
import modelo.Reserva;
import modelo.ServicioCliente;

/**
 *
 * @author USER
 */
public final class VCheckIngCheckOut extends javax.swing.JInternalFrame {
     int nHabitacion;
    /**
     * Creates new form VCheckIngCheckOut
     */
    public VCheckIngCheckOut() {
        
        initComponents();
        numReservas(jcReservas);
        numHabitaciones(jcNumHabitacion);
        numeroRegistros(jcRegistros);
        jlNumRegistro.setVisible(false);
        jbReserva.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jbReserva = new javax.swing.JButton();
        jbRegistro = new javax.swing.JButton();
        jlCodChecking = new javax.swing.JLabel();
        jcReservas = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDIngreso = new com.toedter.calendar.JDateChooser();
        jDSalida = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jcNumHabitacion = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jtxtNumPersonas = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jlNumRegistro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcRegistros = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripciones = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jlIDCliente = new javax.swing.JLabel();
        jlValorHospedaje = new javax.swing.JLabel();
        jlValorServicios = new javax.swing.JLabel();
        jbPagar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jlDias = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdFechaPago = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jlValorTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlNumeroPago = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setIconifiable(true);
        setTitle("Registros y Pagos");

        jbReserva.setText("Checking con reserva");
        jbReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReservaActionPerformed(evt);
            }
        });

        jbRegistro.setText("Checking normal");
        jbRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistroActionPerformed(evt);
            }
        });

        jlCodChecking.setText("Seleccione la Reserva: ");

        jcReservas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcReservasItemStateChanged(evt);
            }
        });

        jLabel1.setText("Identificacion cliente: ");

        jLabel3.setText("Fecha Ingreso: ");

        jLabel4.setText("Fecha Salida: ");

        jLabel5.setText("Numero de Habitacion:");

        jLabel6.setText("Numero de personas: ");

        jbGuardar.setText("Finalizar Registro");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jlNumRegistro.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jbReserva)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jcReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlNumRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcNumHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(56, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jbGuardar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReserva)
                    .addComponent(jbRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlNumRegistro)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCodChecking)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addComponent(jDIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcNumHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtNumPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jbGuardar)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Check - In", jPanel1);

        jcRegistros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcRegistrosItemStateChanged(evt);
            }
        });

        jLabel10.setText("Numero de registro: ");

        jLabel7.setText("Identificacion Cliente:");

        jLabel8.setText("Valor Hospedaje:");

        jLabel12.setText("Valor Servicios:");

        jTADescripciones.setColumns(20);
        jTADescripciones.setRows(5);
        jScrollPane1.setViewportView(jTADescripciones);

        jLabel13.setText("Descripcion:");

        jlIDCliente.setText("...");

        jlValorHospedaje.setText("...");

        jlValorServicios.setText("...");

        jbPagar.setText("Finalizar Y Pagar");
        jbPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPagarActionPerformed(evt);
            }
        });

        jLabel9.setText("Dias:");

        jlDias.setText("...");

        jLabel11.setText("Fecha De Pago:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel14.setText("Valor Total A Pagar:");

        jlValorTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jlValorTotal.setText("...");

        jLabel15.setText("Numero De Pago:");

        jlNumeroPago.setText("...");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlIDCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jlValorHospedaje, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jlDias, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jlValorServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jdFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcRegistros, 0, 107, Short.MAX_VALUE)
                    .addComponent(jlNumeroPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jbPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlNumeroPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlIDCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlValorHospedaje, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlDias, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlValorServicios)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdFechaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlValorTotal)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addComponent(jbPagar)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Check - Out y Pago", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcReservasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcReservasItemStateChanged
        if (jcReservas.getSelectedIndex() == -1) {
        } else {
            int numero = Integer.parseInt(jcReservas.getSelectedItem().toString());
            llenarCheckingReserva(numero);
        }
    }//GEN-LAST:event_jcReservasItemStateChanged

    private void jbReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReservaActionPerformed
        jlCodChecking.setText("Seleccione la Reserva: ");
        jcReservas.setVisible(true);
        jlNumRegistro.setVisible(false);
        jbRegistro.setEnabled(true);
        jbReserva.setEnabled(false);
        limpiarCampos();
    }//GEN-LAST:event_jbReservaActionPerformed

    private void jbRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistroActionPerformed
        jlCodChecking.setText("Numero Registro: ");
        jcReservas.setVisible(false);
        jlNumRegistro.setVisible(true);
        generarNumRegistro();
        jbReserva.setEnabled(true);
        jbRegistro.setEnabled(false);
        limpiarCampos();
    }//GEN-LAST:event_jbRegistroActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        crearRegistro();
        jcReservas.removeAllItems();
        numReservas(jcReservas);
        limpiarCampos();
        dispose();
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jcRegistrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcRegistrosItemStateChanged
       if (jcReservas.getSelectedIndex() == -1) {
        } else {
            int numero = Integer.parseInt(jcRegistros.getSelectedItem().toString());
            llenarCheckOutgRegistros(numero);
        }
    }//GEN-LAST:event_jcRegistrosItemStateChanged

    private void jbPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPagarActionPerformed
        // TODO add your handling code here:
        if(jdFechaPago.getDate()==null){
            JOptionPane.showMessageDialog(this,"Por Favor Introduzca Fecha De Pago");
            jdFechaPago.requestFocusInWindow();
        }else{
        
        
        Pago unPago = new Pago();
        unPago.setNumeroPago(Integer.parseInt(jlNumeroPago.getText()));
        unPago.setIdCliente(Integer.parseInt(jlIDCliente.getText()));
        unPago.setValor(Double.parseDouble(jlValorTotal.getText()));
        java.util.Date dateP = jdFechaPago.getDate();
        long i = dateP.getTime();
        java.sql.Date fechaPago = new java.sql.Date(i);
        unPago.setFechaPago(fechaPago);
        
        int tamaño;
        tamaño=ControladorPago.listadoPago(unPago.getNumeroPago()+"").size();
        
        if(tamaño==0){
            int resultado=0;
            resultado=ControladorPago.grabarPago(unPago);
            if(resultado == 1){
                        JOptionPane.showMessageDialog(this,
                                "Pago Grabado con éxito",
                                "Confirmación",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this,"Error al grabar Pago",
                                "Confirmación",JOptionPane.ERROR_MESSAGE);
                    }
            eliminarRegistro(Integer.parseInt(jlNumeroPago.getText()));            
            jlNumeroPago.setText("...");
            jlIDCliente.setText("...");
            jlValorHospedaje.setText("...");            
            jlDias.setText("...");
            jlValorServicios.setText("...");
            jdFechaPago.setDate(null);
            jTADescripciones.setText("");
            jlValorTotal.setText("...");
            
            modificarEstadoHabPagada(nHabitacion);
            
            dispose();
                        
        
        }
        
        }
    }//GEN-LAST:event_jbPagarActionPerformed

    public void llenarCheckOutgRegistros(int n){
        ArrayList<Registro> listadoRegistro = new ArrayList();
        listadoRegistro = ControladorRegistro.listadoRegistro();
        for (int i = 0; i < listadoRegistro.size(); i++) {
            if (listadoRegistro.get(i).getCodigoRegistro() == n) {
                jlIDCliente.setText(""+ listadoRegistro.get(i).getCodCliente());
                nHabitacion=listadoRegistro.get(i).getNumeroHabitacion();
                buscarHabitacion(listadoRegistro.get(i).getNumeroHabitacion());
                int numeroDias =(int)(( listadoRegistro.get(i).getFechaSalida().getTime() - listadoRegistro.get(i).getFechaEntrada().getTime())/86400000);
                jlDias.setText(""+numeroDias);
                valorServicios(listadoRegistro.get(i).getCodCliente(),listadoRegistro.get(i).getFechaEntrada(),listadoRegistro.get(i).getFechaSalida());
                
                double valorHospedaje= Double.parseDouble(jlValorHospedaje.getText());
                double valorServicios = Double.parseDouble(jlValorServicios.getText());
                double valorTotal= (numeroDias * valorHospedaje )+ valorServicios;
                jlNumeroPago.setText(jcRegistros.getSelectedItem().toString());
                                
                jlValorTotal.setText(""+valorTotal);
                
            }
        }   
                
        
    }
      
    public void buscarHabitacion(int numHabitacion){
        ArrayList<Habitacion> listadoHabitacion = new ArrayList();
        listadoHabitacion = ControladorHabitacion.listadoHabitaciones();
        double valor=0.0; 
        
        for(int i =0; i<listadoHabitacion.size();i++){
            if(listadoHabitacion.get(i).getNumero()==numHabitacion){
                valor=listadoHabitacion.get(i).getValor();
            }
        }
         jlValorHospedaje.setText(""+valor);  
    }
    public void valorServicios(int id_cliente, Date i, Date s){
        ArrayList<Double> servicios=new ArrayList();
        servicios=ControladorServicioCliente.listaValorServicios(id_cliente, i, s);
        double valorServicios=0.0;
        
        for(int x=0;x<servicios.size();x++){
            valorServicios= valorServicios + servicios.get(x);
        }        
        jlValorServicios.setText(""+valorServicios);
        
        ArrayList<String> descripciones=new ArrayList();
        descripciones=ControladorServicioCliente.listaServicios(id_cliente, i, s);
        String descripcion="";       
        for(int x=0;x<descripciones.size();x++){
              descripcion+=descripciones.get(x)+"................ $ "+ servicios.get(x)+"\n";
            }        
        jTADescripciones.setText(descripcion);
        
    }   
    
    public void eliminarRegistro(int cod){
        if(buscarRegistro(cod)){
            int resultado=0;
            resultado=ControladorRegistro.borrarRegistro(cod+"");
            if(resultado==1){
              JOptionPane.showMessageDialog(this,
                        "Se elimino el registro asociada al pago",
                        "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error Al Eliminar Registro",
                        "Confirmación", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    
    
     
    
    //eliminarreserva : elimina la reserva que tenga el codigo ingresado
    public void eliminarReserva(int cod) {
        if (buscarReserva(cod)) {
            int resultado = 0;
            resultado = ControladorReserva.eliminarReserva(cod);
            if (resultado == 1) {
                JOptionPane.showMessageDialog(this,
                        "Se elimino la reserva asociada al registro",
                        "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error Al Eliminar Reserva",
                        "Confirmación", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    //buscarReserva : retorna true si la reserva ingresada existe en la base de datos o false si no
    public boolean buscarReserva(int cod) {
        ArrayList<Reserva> listadoReservas = new ArrayList();
        listadoReservas = ControladorReserva.listadoReserva();
        for (int i = 0; i < listadoReservas.size(); i++) {
            if (listadoReservas.get(i).getCodigoReserva() == cod) {
                return true;
            }
        }
        return false;
    }

    //buscarRegistro : retorna true si el registro ingresado existe en la base de datos o false si no
    public boolean buscarRegistro(int cod) {
        ArrayList<Registro> listadoRegistro = new ArrayList();
        listadoRegistro = ControladorRegistro.listadoRegistro();
        for (int i = 0; i < listadoRegistro.size(); i++) {
            if (listadoRegistro.get(i).getCodigoRegistro() == cod) {
                return true;
            }
        }
        return false;
    }

    // generarNumRegistro : genera un numero de registro que no exista en la base de datos
    public void generarNumRegistro() {
        String num = "";
        int codReserva;
        for (int i = 0; i < 3; i++) {
            int valorAle = (int) Math.floor(Math.random() * 9);
            num = num + valorAle;
        }
        codReserva = parseInt(num);

        if (buscarReserva(codReserva) || buscarRegistro(codReserva)) {
            generarNumRegistro();
        } else {
            jlNumRegistro.setText(num);
        }
    }

    //llenarCheckingReserva : llena los campos con la informacion de la reserva seleccionada
    public void llenarCheckingReserva(int numReserva) {
        ArrayList<Reserva> listadoReserva = new ArrayList();
        listadoReserva = ControladorReserva.listadoReserva();
        for (int i = 0; i < listadoReserva.size(); i++) {
            if (listadoReserva.get(i).getCodigoReserva() == numReserva) {
                jtxtId.setText("" + listadoReserva.get(i).getCodCliente());
                java.sql.Date fechaBaseI = listadoReserva.get(i).getFechaEntrada();
                jDIngreso.setDate(fechaBaseI);
                java.sql.Date fechaBaseS = listadoReserva.get(i).getFechaSalida();
                jDSalida.setDate(fechaBaseS);
                seleccionarHabitacion(listadoReserva.get(i).getNumeroHabitacion());
                jtxtNumPersonas.setText("" + listadoReserva.get(i).getCantidadPersonas());

            }
        }
    }

    //seleccionarHabitacion : selecciona la habitacion asignada a la reserva dada en el combo box 
    public void seleccionarHabitacion(int numero) {
        jcNumHabitacion.setSelectedItem(numero);
    }
    
    public void numeroRegistros(JComboBox j){
        ArrayList<Registro> listadoRegistros= new ArrayList();
        listadoRegistros= ControladorRegistro.listadoRegistro();
        for(int i=0;i<listadoRegistros.size();i++){
            j.addItem(listadoRegistros.get(i).getCodigoRegistro());
        }
    }
    

    //numReserva : agrega el numero de las reservas existentes
    public void numReservas(JComboBox j) {
        ArrayList<Reserva> listadoReserva = new ArrayList();
        listadoReserva = ControladorReserva.listadoReserva();
        for (int i = 0; i < listadoReserva.size(); i++) {
            j.addItem(listadoReserva.get(i).getCodigoReserva());
        }
    }

    //numHabitacion : agrega el numero de las habitaciones existentes
    public void numHabitaciones(JComboBox j) {
        ArrayList<Habitacion> listadoHabitacion = new ArrayList();
        listadoHabitacion = ControladorHabitacion.listadoHabitaciones();
        for (int i = 0; i < listadoHabitacion.size(); i++) {
            j.addItem(listadoHabitacion.get(i).getNumero());
        }
    }

    // verificarFechas : verifica que para una habitacion no se crucen las fechas de reserva
    public boolean verificarFechas() {
        java.util.Date fechaNuevaI = jDIngreso.getDate();
        java.util.Date fechaNuevaS = jDSalida.getDate();
        int numHabitacion = (int) jcNumHabitacion.getSelectedItem();
        ArrayList<Reserva> listadoReservas = new ArrayList();
        listadoReservas = ControladorReserva.listadoReserva();
        for (Reserva r : listadoReservas) {
            if (r.getNumeroHabitacion() == numHabitacion) {
                java.sql.Date fechaBaseI = r.getFechaEntrada();
                java.sql.Date fechaBaseS = r.getFechaSalida();
                if (fechaNuevaI.after(fechaBaseI) && fechaNuevaI.before(fechaBaseS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " Ya se encuentra reservada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
                if (fechaNuevaS.after(fechaBaseI) && fechaNuevaS.before(fechaBaseS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " Ya se encuentra reservada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
                if (fechaBaseI.after(fechaNuevaI) && fechaBaseI.before(fechaNuevaS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " Ya se encuentra reservada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
                if (fechaBaseS.after(fechaNuevaI) && fechaBaseS.before(fechaNuevaS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " Ya se encuentra reservada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
            }
        }
        for (Registro re : ControladorRegistro.listadoRegistro()) {
            if (re.getNumeroHabitacion() == numHabitacion) {
                java.sql.Date fechaBaseI = re.getFechaEntrada();
                java.sql.Date fechaBaseS = re.getFechaSalida();
                if (fechaNuevaI.after(fechaBaseI) && fechaNuevaI.before(fechaBaseS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " se encuentra ocupada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
                if (fechaNuevaS.after(fechaBaseI) && fechaNuevaS.before(fechaBaseS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " se encuentra ocupada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
                if (fechaBaseI.after(fechaNuevaI) && fechaBaseI.before(fechaNuevaS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " se encuentra ocupada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
                if (fechaBaseS.after(fechaNuevaI) && fechaBaseS.before(fechaNuevaS)) {
                    JOptionPane.showMessageDialog(this, "La habitacion : " + numHabitacion + " se encuentra ocupada desde la fecha : " + fechaBaseI
                            + " hasta la fecha : " + fechaBaseS);
                    return true;
                }
            }
        }
        return false;
    }

    //crearReserva :  crea la reserva si toda la informacion esta completa
    public void crearRegistro() {
        
        if (camposVacios() && !verificarFechas()) {
            java.util.Date dateI = jDIngreso.getDate();
            java.util.Date dateS = jDSalida.getDate();
            long i = dateI.getTime();
            long s = dateS.getTime();
            java.sql.Date fechaI = new java.sql.Date(i);
            java.sql.Date fechaS = new java.sql.Date(s);
            Registro unRegistro = new Registro();
            if (!jbRegistro.isEnabled()) {
                unRegistro.setCodigoRegistro(parseInt(jlNumRegistro.getText()));
            } else {
                unRegistro.setCodigoRegistro(Integer.parseInt(jcReservas.getSelectedItem().toString()));
            }
            unRegistro.setNumeroHabitacion(Integer.parseInt(jcNumHabitacion.getSelectedItem().toString()));
            unRegistro.setCodCliente(parseInt(jtxtId.getText()));
            unRegistro.setFechaEntrada(fechaI);
            unRegistro.setFechaSalida(fechaS);
            unRegistro.setCantidadPersonas(parseInt(jtxtNumPersonas.getText()));

            int resultado = 0;
            resultado = ControladorRegistro.crearRegistro(unRegistro);
            if (resultado == 1) {
                eliminarReserva(unRegistro.getCodigoRegistro());
                modificarEstadoHab(unRegistro.getNumeroHabitacion());
                JOptionPane.showMessageDialog(this,
                        "Registro Reaizado Con éxito",
                        "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error Al Realizar Registro",
                        "Confirmación", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // camposVacios retorna true si todos los campos estan llenos o false si hay campos vacios
    public boolean camposVacios() {
        if ("".equals(jtxtId.getText()) || jDIngreso.getDate()==null || jDSalida.getDate()==null || jcNumHabitacion.getSelectedItem().toString() == "" || "".equals(jtxtNumPersonas.getText())) {
            JOptionPane.showMessageDialog(this, "por favor llene todos los campos");
            return false;
        } else {
            return true;
        }
    }

    // limpìatCampos : borra toda al informacion de la ventana 
    public void limpiarCampos() {
        jtxtId.setText("");
        jDIngreso.setDate(null);
        jDSalida.setDate(null);
        jtxtNumPersonas.setText("");
        jcNumHabitacion.setSelectedIndex(-1);
        jcReservas.setSelectedIndex(-1);
        generarNumRegistro();
    }

    //modificarEstadoHab : Cambia el estado de la habitacion si esta siendo ocupada
    public void modificarEstadoHab(int num) {
        ArrayList<Habitacion> listadoHabitaciones = new ArrayList<>();
        listadoHabitaciones = ControladorHabitacion.listadoHabitaciones();
        for (Habitacion h : listadoHabitaciones) {
            if (h.getNumero() == num) {
                h.setEstado("ocupado");
                int resultado = ControladorHabitacion.modificarHabitacion(h);
                if (resultado == 1) {
                    JOptionPane.showMessageDialog(this,
                            "La habitacion : "+num+" cambio su estado a ocupado",
                            "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error Al Modificar Habitacion",
                            "Confirmación", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    public void modificarEstadoHabPagada(int num) {
        ArrayList<Habitacion> listadoHabitaciones = new ArrayList<>();
        listadoHabitaciones = ControladorHabitacion.listadoHabitaciones();
        for (Habitacion h : listadoHabitaciones) {
            if (h.getNumero() == num) {
                h.setEstado("disponible");
                int resultado = ControladorHabitacion.modificarHabitacion(h);
                if (resultado == 1) {
                    JOptionPane.showMessageDialog(this,
                            "La habitacion : "+num+" cambio su estado a disponible",
                            "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Error Al Modificar Habitacion",
                            "Confirmación", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDIngreso;
    private com.toedter.calendar.JDateChooser jDSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripciones;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbPagar;
    private javax.swing.JButton jbRegistro;
    private javax.swing.JButton jbReserva;
    private javax.swing.JComboBox<String> jcNumHabitacion;
    private javax.swing.JComboBox<String> jcRegistros;
    private javax.swing.JComboBox<String> jcReservas;
    private com.toedter.calendar.JDateChooser jdFechaPago;
    private javax.swing.JLabel jlCodChecking;
    private javax.swing.JLabel jlDias;
    private javax.swing.JLabel jlIDCliente;
    private javax.swing.JLabel jlNumRegistro;
    private javax.swing.JLabel jlNumeroPago;
    private javax.swing.JLabel jlValorHospedaje;
    private javax.swing.JLabel jlValorServicios;
    private javax.swing.JLabel jlValorTotal;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtNumPersonas;
    // End of variables declaration//GEN-END:variables
}
